commented unused import
OpenSouceCode/Frontend pull request #228
Opened 2020-09-17 13:44 UTC by FaizanKhan7

This PR solves issue #

**What does this PR do?**

**Any background context you want to provide?**

**Screenshots?**

2020-09-17 17:22 UTC, vipulsnp requested changes

2020-09-17 17:22 UTC, vipulsnp commented on pages/project/[pid].jsx
> +          <h1>Open Source Code</h1>
This data should be different for each repo.

2020-09-17 17:22 UTC, vipulsnp commented on pages/project/[pid].jsx
> +                <img src="/icons/github-icon.png" alt="Github-icon" />
Change it to a button and add `link` to the github repository.

2020-09-17 17:22 UTC, vipulsnp commented on pages/project/[pid].jsx
> +                <img src="/icons/gitPod-icon.png" alt="Gitpod-icon" />
Add gitpod link here and change to button

2020-09-17 17:22 UTC, vipulsnp commented on pages/project/[pid].jsx
> +              <p>By Organisation | 08 May 2020</p>
`Date` and `Organisation name` Should be from repo data

2020-09-17 17:22 UTC, vipulsnp commented on pages/project/[pid].jsx
> +              There should be some content her. So I am filling this with random
`Description` should be from from repo data

2020-09-17 17:22 UTC, vipulsnp commented on pages/project/[pid].jsx
> +              <span className={styles['org-lang-1']}>Javascript</span>
the `language` tags should be from the repo data.

2020-09-22 19:41 UTC, vipulsnp requested changes
@FaizanKhan7 
1. Add `description` .
2. 
![image](https://user-images.githubusercontent.com/41316371/93929398-6e142a80-fd39-11ea-9326-9bf4cbba2077.png) Not properly aligned `forks` `stars` and text
3. 
![image](https://user-images.githubusercontent.com/41316371/93929447-7e2c0a00-fd39-11ea-939f-2fc04196dbe9.png)
make the size of buttons smaller on Mobile view
4. Align the name of repo to center on Mobile view

2020-09-23 07:35 UTC, FaizanKhan7 commented
## Resolved Requested changes 
![image](https://user-images.githubusercontent.com/53424289/93981237-54a4ca00-fd9d-11ea-946b-14a3bf84f8ba.png)
![image](https://user-images.githubusercontent.com/53424289/93981354-7ef68780-fd9d-11ea-8d35-b78c68a81f2d.png)

2020-09-23 18:13 UTC, vipulsnp approved these changes

2020-09-23 18:13 UTC, merged